version: '3.6'
services:
  nuxt:
    build:
      context: ./
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: atlas-search
    ports:
      - '3000:3000'
    command: 'yarn start'
    restart: always
  nginx:
    container_name: nginx
    image: library/nginx:1.19.0
    tty: true
    ports:
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
    restart: unless-stopped
    links:
      - nuxt
